### ISSUE TITLE
How to hide alt text and title button?

### ISSUE THREAD

**Issue by zAlweNy26** [enzedonline/quill-blot-formatter2#6]
I'd like to hide the button that opens the modal to add `title` and `alt text` to the image. How can I achieve it? Thanks for the help in advance.

**Comment by zAlweNy26** [comment]
Hi @bubbleheadinc thanks for the workaround, I didn't think about that! Anyway I hope to have a way to do it within the options of this module, as this workaround is very dirty as you say ahah

**Comment by enzedonline** [comment]
Yep, I'll add an option to the image path in the next release (css as a workaround until then 😉)
```javascript
{
  image: {
    allowAltTitleEdit: true
  }
}
```

**Comment by enzedonline** [comment]
Scrub that ... To avoid a substantial rewrite, I've added it to the `align.toolbar` path. This project is like butterfly effect, small change here, hurricane there 😂The perils of inheriting someone else's old code.
```javascript
{
  align: {
    toolbar: {
      allowAltTitleEdit: true
    }
  }
}
```
Maybe I should have just made a clean break from the original package, I was trying to maintain portability. Anyway, it'll be included in the next release, I'll update here when that happens.

**Comment by zAlweNy26** [comment]
@enzedonline do you have any update on the next release date for this feature?

**Comment by enzedonline** [comment]
I ended up rewriting of much of the code to fix a lot of the inherited bugs and enable for touch screen. I've added support for relative sizing now too.
Not quite finished testing, but I think it's more or less done.
You can test the compiled version if you like, downloadable from [here](https://1drv.ms/f/s!AppilyLm3gHit4dluxCw6G0Yh2JcmA?e=EGodlc). Happy to know if you can find any bugs.
The updated readme is there for reference. 
The solution for this request is back to my first suggestion:
```
{
  image: {
    allowAltTitleEdit: true
  }
}
```

**Comment by enzedonline** [comment]
v2.2.0 released now. Alt/title editing disabled by:

```
  image: {
    allowAltTitleEdit: false,
  },
```
