### ISSUE TITLE
Video proxy element not working

### ISSUE THREAD

**Issue by zAlweNy26** [enzedonline/quill-blot-formatter2#9]
I was testing the video resize and saw that proxy thing you did, so I added the border suggested by the README to see why it was not correctly appearing when I tried to resize the video element.
![image](https://github.com/user-attachments/assets/e211470f-098c-44a0-a790-0fd884568eef)
And I got this, the proxy never contains the video perfectly, but is always above a few pixels, depending on the size of the video element, the bigger the video, the further away the proxy.

**Comment by enzedonline** [comment]
I can't replicate this. Can you share some details of your configuration?

Browser? OS? 
Is the editor or any ancestor scrollable? If so, does it happen in any scrolled position?

**Comment by zAlweNy26** [comment]
Browser: Firefox
OS: Ubuntu
Yes, there is a scrollable ancestor (like 2 or 3 level above, can't check atm). Yes, but as I said, it moves closer or further away based on the width of the video.

**Comment by enzedonline** [comment]
> Yes, but as I said, it moves closer or further away based on the width of the video.

This is what happened on the old version with a scrollable editor, made me think something in your layout is triggering this still.

I could replicate something similar with multiple scrollable elements (editor, form and document in the screenshot) when the intermediate scrollable is not at scroll.top. The width doesn't affect the vertical displacement amount however with this however, just the intermediate scroll position affects that.

Form scrollable, at scroll.top, aligns correctly:

![localhost_8000_posts_40_edit_](https://github.com/user-attachments/assets/aa06dabb-20f6-4ab4-b3f3-098a86cc7d67)

Form scrollable, at scrolled down position, aligns incorrectly:

![localhost_8000_posts_40_edit_ (1)](https://github.com/user-attachments/assets/260ea33b-648c-437b-84de-03c66df92bb9)

I've tracked down & resolved that bug (and another when clicking from one video to another). 

Can you test with this compiled js?

[quill-blot-formatter2.min.zip](https://github.com/user-attachments/files/16988325/quill-blot-formatter2.min.zip)

**Comment by zAlweNy26** [comment]
Hi thanks for answering, can you please provide the package zip with the types? it's a bit hard to replicate in my environment with a minified js file.

**Comment by enzedonline** [comment]
Can you get it from the dist folder here?
https://1drv.ms/f/s!AppilyLm3gHitJQj2z6drpttDk3XAw

Late night here, not near my pc 😉

**Comment by zAlweNy26** [comment]
Still the same, these are my settings:
```js
blotFormatter2: {
	align: {
		allowAligning: false,
	},
	resize: {
		allowResizing: true,
		useRelativeSize: true,
		allowResizeModeChange: true,
	},
	delete: {
		allowKeyboardDelete: true,
	},
	image: {
		allowAltTitleEdit: false,
	},
	video: {
		registerCustomVideoBlot: true,
		registerBackspaceFix: true,
		proxyStyle: {
			border: '5px red solid',
			zIndex: 50,
		},
	},
}
```

maybe it's a problem with my project? the editor is in a modal that's why I increased the z-index.

**Comment by enzedonline** [comment]
I shouldn't think the z-index would make any difference. Weird thing is the screenshot you shared shows the overlay in the correct place. That last edit changed the proxy positioning code to use exactly the same logic as the overlay (I should have done that after I moved the proxies into the Quill container instead of being appended to the doc body).

Can you share the modal html and any relevant css, I'll see if I can replicate it.

**Comment by enzedonline** [comment]
Hmm, I changed my form to use a modal, it still displays correctly:

![image](https://github.com/user-attachments/assets/c7e62b81-8353-4b76-85f4-ff02d1a22fa5)

I'll wait for your html & css

**Comment by zAlweNy26** [comment]
Hi, sorry for the delay, here it is the HTML file (I don't have a CSS file to pass because I'm using tailwind, so it's a bit useless to give you the generated CSS):
[modal.zip](https://github.com/user-attachments/files/17009618/modal.zip)

**Comment by enzedonline** [comment]
Oof. No, I can't reconstruct it from that HTML without the CSS or knowing where & how you're implementing Quill there.

I've tried every combination of floating elements, absolute positions, scrollable containers, nesting multiple of each even, still can't replicate this.

If you click on a misplaced proxy, does the formatter overlay sit on the iframe or the proxy? It looks from your screenshot that the overlay is in the correct position over the iframe.

It's exactly the same logic that positions both:

```typescript
  private repositionOverlay() {
    if (this.currentSpec) {
      const overlayTarget = this.currentSpec.getOverlayElement();
      if (overlayTarget) {
        const containerRect: DOMRect = this.quill.container.getBoundingClientRect();
        const specRect: DOMRect = overlayTarget.getBoundingClientRect();
        Object.assign(this.overlay.style, {
          display: 'block',
          left: `${specRect.left - containerRect.left - 1 + this.quill.container.scrollLeft}px`,
          top: `${specRect.top - containerRect.top + this.quill.container.scrollTop}px`,
          width: `${specRect.width}px`,
          height: `${specRect.height}px`,
        });
      }
    }
  }
```

```typescript
  repositionProxyImages(): void {
    if (Object.keys(this.unclickableProxies).length > 0) {      
      const containerRect: DOMRect = this.formatter.quill.container.getBoundingClientRect();
      const containerScrollLeft: number = this.formatter.quill.container.scrollLeft;
      const containerScrollTop: number = this.formatter.quill.container.scrollTop;

      Object.entries(this.unclickableProxies).forEach(([key, { unclickable, proxyImage }]) => {
        try {
          // Calculate the unclickable's position relative to the container
          const unclickableRect: DOMRect = unclickable.getBoundingClientRect();
          Object.assign(proxyImage.style, {
              left: `${unclickableRect.left - containerRect.left - 1 + containerScrollLeft}px`,
              top: `${unclickableRect.top - containerRect.top + containerScrollTop}px`,
              width: `${unclickableRect.width}px`,
              height: `${unclickableRect.height}px`,
            },
          );
        } catch (error) {
          const msg: string = `Error positioning proxy image with id ${key}: `
          console.error(msg, `${error instanceof Error ? error.message : error}`);
        }
      });
    }
  }
```

^ Unclickable is just the iframe instance.

**Comment by enzedonline** [comment]
Happy to look into this if you can send me reproducible code. Not much I can do about it without that. 
I've released the patch with the 2 bug fixes now (2.2.1).

**Comment by zAlweNy26** [comment]
Yeah sorry, I'll try the new release!

**Comment by zAlweNy26** [comment]
Awesome, it works! Maybe I did something wrong trying to install the zip you gave to me, sorry for the trouble

**Comment by enzedonline** [comment]
Ah, brilliant. That solves that mystery then 😉
